jobs:
  jenkins_io_draft:
    if: github.repository_owner == 'jenkinsci'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: generate-token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.JENKINS_CHANGELOG_UPDATER_APP_ID }}
        installation_retrieval_mode: repository
        installation_retrieval_payload: jenkins-infra/jenkins.io
        private_key: ${{ secrets.JENKINS_CHANGELOG_UPDATER_PRIVATE_KEY }}
        repositories: '["jenkins.io"]'
    - continue-on-error: true
      name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      env:
        GITHUB_AUTH: nobody:${{ steps.generate-token.outputs.token }}
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        GIT_AUTHOR_EMAIL: <86592549+jenkins-infra-changelog-generator[bot]@users.noreply.github.com>
        GIT_AUTHOR_NAME: jenkins-infra-changelog-generator
        GIT_COMMITTER_EMAIL: <86592549+jenkins-infra-changelog-generator[bot]@users.noreply.github.com>
        GIT_COMMITTER_NAME: jenkins-infra-changelog-generator
      name: Publish jenkins.io changelog draft
      run: 'wget --quiet https://raw.githubusercontent.com/jenkinsci/core-changelog-generator/master/generate-weekly-changelog.sh

        bash generate-weekly-changelog.sh

        '
  update_draft_release:
    if: github.repository_owner == 'jenkinsci'
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: release-drafter
      name: Generate GitHub Release Draft
      uses: release-drafter/release-drafter@v6
    - continue-on-error: true
      env:
        GITHUB_AUTH: github-actions:${{ secrets.GITHUB_TOKEN }}
      id: jenkins-core-changelog-generator
      name: Generate YAML changelog draft
      uses: jenkinsci/jenkins-core-changelog-generator@master
    - continue-on-error: true
      name: Upload Changelog YAML
      uses: actions/upload-artifact@v4
      with:
        name: changelog.yaml
        path: changelog.yaml
name: Changelog Drafter
on:
  repository_dispatch:
    types: trigger-ga___changelog.yml
permissions:
  contents: read
