jobs:
  label:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: startsWith(github.event.pull_request.base.ref, 'stable-')
      name: Check if PR targets LTS branch
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "github.rest.issues.addLabels({\n  owner: context.payload.repository.owner.login,\n\
          \  repo: context.payload.repository.name,\n  issue_number: context.payload.pull_request.number,\n\
          \  labels: ['into-lts']\n});\n"
name: Label PRs targeting LTS branches
on:
  repository_dispatch:
    types: trigger-ga___label-lts-prs.yaml
permissions:
  pull-requests: write
